allowedImageFormats = ['.jpg', '.png', '.tga', '.psd', '.psb', '.exr', '.hdr', '.mpic', '.bmp', '.dds', '.tig', '.pfm']
saveFormats = ['.psd', '.tga', '.png', '.jpg', 'jpeg']
bakeResolutions = ['64', '128', '256', '512', '1024', '2048', '4096', '8192']
bakeSamples = ['1', '4', '16', '64']
bakerMesh = 'data/Quad.obj'
configFile = 'settings.ini'
pyfile = 'MarmosetBaker.py'
defaultRecipeFile = 'data/.bakerRecipe'
fancyParametersNames = {'_savePath': 'Save Location', '_saveName': 'Save Name'}
transparencyTexture = 'data/transparency.png'
textureWhite = 'data/white.tif'
textureBlack = 'data/black.tif'
